name:                CliNotifier
version:             0.0.1
github:              "mlopes/CliNotifier"
license:             BSD3
author:              "Marco Lopes"
maintainer:          "Marco Lopes"
copyright:           "2019 Marco Lopes"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/CliNotifier#readme>

dependencies:
- base >= 4.7 && < 5
- linklater
- mtl
- text
- time
- process

default-extensions:
- FlexibleContexts

library:
  source-dirs: src

executables:
  CliNotifier-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CliNotifier

tests:
  CliNotifier-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CliNotifier
